language: python
python: "3.9"
dist: xenial

env:
  POETRY_VIRTUALENVS_CREATE: false

stages:
  - Quality

jobs:
  include:
    - stage: Quality
      name: lint
      install: pip install pylint
      script: pylint --disable=missing-class-docstring simpleurdf
    - name: type
      before_install:
        - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
      install: npm install -g pyright
      script: pyright
    - name: tests
      before_install:
        - npm install -g pyright
        - pip install poetry
      install: poetry install -vv
      script: pytest
