language: python
python: "3.9"
dist: xenial

before_install:
  - pip install poetry
  - poetry --version
  - poetry config settings.virtualenvs.in-project true
install:
  - poetry install -vv
script:
  - pytest