language: python
python: "3.9"
dist: xenial

env:
  POETRY_VIRTUALENVS_CREATE: false

stages:
  - Build
  - Quality

jobs:
  include:
    - stage: Build
      before_install:
        - npm install -g pyright
        - pip install poetry
        - poetry --version
      install:
        - poetry install -vv
    - stage: Quality
      name: lint
      script: pylint simpleurdf
    - name: type
      script: pyright simpleurdf
    - name: tests
      script: pytest
