language: python
python: "3.9"
dist: xenial

env:
  POETRY_VIRTUALENVS_CREATE: false

stages:
  - Build
  - Quality

jobs:
  include:
    - stage: Build
      before_install:
        - npm install -g pyright
        - pip install poetry
      install:
        - poetry install -vv
      script: poetry --version
    - stage: Quality
      name: lint
      install: pip install pylint
      script: pylint simpleurdf
    - name: type
      install: npm install -g pyright
      script: pyright simpleurdf
    - name: tests
      script: pytest
